service: matt-cognito-hop-client-backend

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 10
  environment: ${file(./.env.${self:provider.stage}.yml)}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ORDERS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MAIN_TABLE}

functions:
  # HTTP APIs
  getOrders:
    handler: app.handlers.http.get_orders.handler
    description: "Get all orders for authenticated user"
    events:
      - httpApi:
          path: /orders
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false 